### ISSUE TITLE
TypeError: Cannot read property 'authenticateuser' of null

### ISSUE THREAD

**Issue by pmk010** [seishun/node-steam#115]
I recently updated to v0.12 and so updated node-steam along with everything I use. I have since been encountering this error every time I try to start a bot.

```
F:\Nodejs Steam\<edited>\node_modules\steam\lib\handlers\user.js:106
          'steamLogin=' + response.authenticateuser.token,
                                  ^
TypeError: Cannot read property 'authenticateuser' of null
    at IncomingMessage.<anonymous> (F:\Nodejs Steam\<edited>\node_modules\steam\
lib\handlers\user.js:106:35)
    at IncomingMessage.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at onEofChunk (_stream_readable.js:401:3)
    at readableAddChunk (_stream_readable.js:146:7)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnMessageComplete (_http_common.js:154:14)
    at TLSSocket.socketOnData (_http_client.js:310:20)
    at TLSSocket.emit (events.js:107:17)

F:\Nodejs Steam\<edited>>PAUSE
```

**Comment by seishun** [comment]
Could you paste a minimal test case that reproduces this?

**Comment by pmk010** [comment]
```
var username = "";
var password = "";

var steamGuard = require("fs").readFileSync("sentryfile");

var Steam = require("steam");
var SteamTrade = require("steam-trade");

var steam = new Steam.SteamClient();
var steamTrade = new SteamTrade();

steam.logOn({
	accountName: username,
	password: password
		,shaSentryfile: steamGuard
});

steam.on("debug", console.log);

steam.on("loggedOn", function(result) {
	console.log("Logged in.");
    steam.setPersonaState(Steam.EPersonaState.Online);
});

steam.on("webSessionID", function(sessionID) {
    console.log("Got a new session ID:", sessionID);
    steamTrade.sessionID = sessionID;
    steam.webLogOn(function(cookies) {
        cookies.forEach(function(cookie) {
            steamTrade.setCookie(cookie);
        });
	});
});
```

Seems to be to do with webLogOn

**Comment by seishun** [comment]
I can't reproduce the issue with this code. Could you add `console.log(chunk)` above [this line](https://github.com/seishun/node-steam/blob/master/lib/handlers/user.js#L103) and see what it says?

**Comment by pmk010** [comment]
My user.js file, around the same line number appears to be different.

```
  var req = require('https').request(options, function(res) {
    if (res.statusCode == 200) {
      res.on('readable', function() {
        var response = JSON.parse(res.read());
        callback([
          'sessionid=' + self._webSessionID,
          'steamLogin=' + response.authenticateuser.token,
          'steamLoginSecure=' + response.authenticateuser.tokensecure
        ]);
      });
    } else {
      self.emit('debug', 'web authentication ' + res.statusCode + ', retrying');
      // request a new login key first
      self._send(EMsg.ClientRequestWebAPIAuthenticateUserNonce | protoMask, schema.CMsgClientRequestWebAPIAuthenticateUserNonce.serialize({}), function() {
        self.webLogOn(callback);
      });
      // discard the data
      res.resume();
    }
  });
```

I installed the latest version today, so I can't see how there could be any discrepancies?

**Comment by seishun** [comment]
You should install from git, the npm version is currently outdated.

**Comment by pmk010** [comment]
Ah okay, I'll do that in a bit and let you know the results

**Comment by jhartzell** [comment]
This was a definite resolution for me, thank you! @seishun

**Comment by seishun** [comment]
I assume this is resolved.
