### ISSUE TITLE
Illegal Buffer?

### ISSUE THREAD

**Issue by Supergovs** [seishun/node-steam#120]
So im trying to run https://github.com/rannmann/node-steam-trade-tutorial/blob/master/app.js and i get this error:
C:\Users\USER\Downloads\USER\Node.js Steam TradeBot>node core.js
C:\Users\USER\Downloads\USER\Node.js Steam TradeBot\node_modules\steam\node_mo
dules\bytebuffer\dist\ByteBufferNB.js:322
throw TypeError("Illegal buffer");
^
TypeError: Illegal buffer
at TypeError (native)
at Function.module.exports.ByteBuffer.wrap (C:\Users\VILNIS\Downloads\Miks\N
ode.js Steam TradeBot\node_modules\steam\node_modules\bytebuffer\dist\ByteBuffer
NB.js:322:19)
at ProtoBuf.Reflect.FieldPrototype.verifyValue (C:\Users\VILNIS\Downloads\Mi
ks\Node.js Steam TradeBot\node_modules\steam\node_modules\protobufjs\dist\ProtoB
uf.js:2728:43)
at MessagePrototype.set (C:\Users\VILNIS\Downloads\Miks\Node.js Steam TradeB
ot\node_modules\steam\node_modules\protobufjs\dist\ProtoBuf.js:1799:63)
at Message (C:\Users\VILNIS\Downloads\Miks\Node.js Steam TradeBot\node_modul
es\steam\node_modules\protobufjs\dist\ProtoBuf.js:1725:42)
at SteamClient.handlers.(anonymous function) (C:\Users\VILNIS\Downloads\Miks
\Node.js Steam TradeBot\node_modules\steam\lib\steam_client.js:177:44)
at SteamClient._netMsgReceived (C:\Users\VILNIS\Downloads\Miks\Node.js Steam
TradeBot\node_modules\steam\lib\steam_client.js:106:26)
at Connection.emit (events.js:107:17)
at Connection._readPacket (C:\Users\VILNIS\Downloads\Miks\Node.js Steam Trad
eBot\node_modules\steam\lib\connection.js:50:8)
at Connection.emit (events.js:104:17)

**Comment by seishun** [comment]
That's because you're passing `undefined` as `shaSentryfile` in [logOn](https://github.com/seishun/node-steam#logonlogondetails). If this property exists at all, it must be a Buffer.
