### ISSUE TITLE
Help... Can't figure this out! [error with function]

### ISSUE THREAD

**Issue by NavyCo** [seishun/node-steam#121]
When I do this...
```node
var Steam = require('steam');
var bot = new Steam.SteamClient();
bot.logOn({
    accountName: 'nico55538',
    password: '**********'
});
bot.on('loggedOn', function() {
    console.log('It Worked!')
});
```
It returns this...
```node
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (C:\Users\Nicholas\node_modules\steam\lib\steam_client.js:150:42)
    at SteamClient._netMsgReceived (C:\Users\Nicholas\node_modules\steam\lib\steam_client.js:106:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (C:\Users\Nicholas\node_modules\steam\lib\connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```
Whats the problem here???

**Comment by scholtzm** [comment]
If you are using latest node-steam, make sure you are running node.js v0.12 or io.js.

**Comment by NavyCo** [comment]
Ok will do...
- 30 seconds later
node -v
v0.10.35
That explains ^^
Will try again!

**Comment by NavyCo** [comment]
Ok Thank you!
But after trying again I got error #11
"InvalidState: 11,"
What does that mean?

**Comment by NavyCo** [comment]
Ok nvm I hate being the faggot from hell who knows nothing but now its saying logon denied... Could it be because it has steamguard?

**Comment by scholtzm** [comment]
You need to provide auth code or sentry file.
See [READ ME](https://github.com/seishun/node-steam#logonlogondetails).

**Comment by NavyCo** [comment]
scholtzm mind if you add me on steam so I can communicate a lil faster?
http://steamcommunity.com/id/NavyCo/

**Comment by scholtzm** [comment]
I'm sure you can figure out the rest on your own. Here are [couple more examples](https://github.com/Alex7Kom/node-steam-tradeoffers/tree/master/examples).

**Comment by seishun** [comment]
Closing since there doesn't seem to be an issue with the library.
