### ISSUE TITLE
crypto has no method publicEncrypt

### ISSUE THREAD

**Issue by gyzerok** [seishun/node-steam#123]
```
.../node_modules/steam/lib/steam_client.js:150
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna

TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (.../node_modules/steam/lib/steam_client.js:150:42)
    at SteamClient._netMsgReceived (.../node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (.../node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

Whats the problem? How to fix it?

**Comment by jabbink** [comment]
Did you try `npm install`?

**Comment by scholtzm** [comment]
Update to node.js v0.12.

**Comment by gyzerok** [comment]
I suppose that acording to the way npm install packages you have to change version to 0.7.0 when migrating to node 0.12.

**Comment by seishun** [comment]
> Note: only Node.js v0.12 and io.js v1.4 are supported.
