### ISSUE TITLE
Cannot call method build of null

### ISSUE THREAD

**Issue by dragonbanshee** [seishun/node-steam#127]
My code returns this error when I try to run it:

```javascript
/Users/Kyle/node_modules/steam/lib/steam_client.js:18
th.join(__dirname, '../resources/protobufs/dota/steammessages.proto')).build()
                                                                       ^
TypeError: Cannot call method 'build' of null
    at Object.<anonymous> (/Users/Kyle/node_modules/steam/lib/steam_client.js:18:109)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Kyle/node_modules/steam-chat-bot/lib/chatBot.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

At these lines of code:
```javascript
Steam.GC = {
  // generated from dota/steammessages.proto
  Internal: ProtoBuf.loadProtoFile(path.join(__dirname, '../resources/protobufs/dota/steammessages.proto')).build()
};
```

I looked where this folder should be and there is no folder called 'protobufs' where the code says there should be.

**Comment by dragonbanshee** [comment]
This was fixed by updating to the most current version of node.
