### ISSUE TITLE
Object #<Object> has no method 'publicEncrypt'

### ISSUE THREAD

**Issue by Sekhmet** [seishun/node-steam#152]
```javascript
node_modules/steam/lib/steam_client.js:150
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (/home/sekhmet/bot/node_modules/steam/lib/steam_client.js:150:42)
    at SteamClient._netMsgReceived (/home/sekhmet/bot/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/home/sekhmet/bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

It happens when running example code

```javascript
var Steam = require('steam');

var bot = new Steam.SteamClient();
bot.logOn({
  accountName: 'ddd2',
  password: 'ddd'
});
bot.on('loggedOn', function() { 
  console.log('Logged in');
});
```

**Comment by seishun** [comment]
You're using an old version of Node.js. Upgrade to Node.js v0.12 or io.js v2.x.

**Comment by Sekhmet** [comment]
Just noticed it. I am updating.

**Comment by CSGOSTAR** [comment]
seishun, hi
I do not know much English ... but could you help me?
I for some reason did not want to run a bot, but rather it is run. But it is not working. Please write to me on Skype .. Help for the money
Skype csgostar.com
