### ISSUE TITLE
Error: This socket is closed

### ISSUE THREAD

**Issue by timeDev** [seishun/node-steam#154]
When I call logOn with an authCode, I get the following error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
    at Connection.Socket._writeGeneric (net.js:656:19)
    at Connection.Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Connection.Writable.write (_stream_writable.js:217:11)
    at Connection.Socket.write (net.js:634:40)
    at Connection.send ([...]\node_modules\steam\lib\connection.js:24:8)
    at SteamClient._send ([...]\node_modules\steam\lib\steam_client.js:75:20)
    at SteamClient.handlers.(anonymous function) ([...]\node_modules\steam\lib\handlers\user.js:229:8)
    at SteamClient._netMsgReceived ([...]\node_modules\steam\lib\steam_client.js:106:26)
```

The error seems to come from `handlers[EMsg.ClientUpdateMachineAuth]`

It happens inconsistently, sometimes I get the error, other times I do not, but I also do not get a sentry. It happens on both of my accounts.

[Gist of my full code](https://gist.github.com/timeDev/dd540ef2666680fb0d49)

**Comment by seishun** [comment]
Interesting. Can you add a `bot.on('debug', console.log)` line somewhere in your code?

**Comment by timeDev** [comment]
It's in there already.

**Comment by seishun** [comment]
Is there any debug output before the error?

**Comment by timeDev** [comment]
```
connecting to 146.66.152.12:27018
connected
encrypt request
handshake complete
Successfully logged on.
Steam ID: [redacted]
```

**Comment by seishun** [comment]
So here's what happens:

1. it receives two messages in a single Multi message: ClientLogOnResponse and ClientUpdateMachineAuth;
2. it handles ClientLogOnResponse and emits 'loggedOn', you call logOff which closes the socket;
3. it handles ClientUpdateMachineAuth which causes it to send a ClientUpdateMachineAuthResponse, which causes the error since the socket is already closed.

I'm not sure how to fix it properly. If I just check for loggedOn and don't send a ClientUpdateMachineAuthResponse in your case, then your sentry will probably be invalid.

**Comment by timeDev** [comment]
Ok, so I'll call logOff once the sentry has been received, no problem.
