### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by dolanmiu** [seishun/node-steam#165]
It seems like sometimes when I login, it throws this:

```
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

It loads the OpenAuth steam login, and then it will take forever to login, then it will throw that timed out error. 

What is going on?

It only started happening recently.

**Comment by dolanmiu** [comment]
Nevermind, I believe this is a passport-steam issue
