### ISSUE TITLE
Crash when logged in

### ISSUE THREAD

**Issue by TheKkubas** [seishun/node-steam#174]
Hi. Some time when i try to log on with node-steam (examples and my code) I get that error.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^

  at SteamClient.handlers.(anonymous function) (/root/SteamBot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/root/SteamBot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/root/SteamBot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/root/SteamBot/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/SteamBot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)

```
What can I do?

**Comment by seishun** [comment]
It would help if you pasted the error as well, not just the stack trace.

**Comment by TheKkubas** [comment]
fixed
