### ISSUE TITLE
Error: Logged off: 34

### ISSUE THREAD

**Issue by strigunov** [seishun/node-steam#177]
What this is ?

connected
encrypt request
handshake complete
Logged in!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Logged off: 34
    at SteamClient.handlers.(anonymous function) (/home/site/node_modules/steam/            lib/handlers/user.js:217:13)
    at SteamClient._netMsgReceived (/home/site/node_modules/steam/lib/steam_clie            nt.js:106:26)
    at SteamClient.handlers.(anonymous function) (/home/site/node_modules/steam/            lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/home/site/node_modules/steam/lib/steam_clie            nt.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/site/node_modules/steam/lib/connection.js:5            0:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
[root@JackBets site]# cd /home/bot
[root@JackBets bot]# node trade.js
connected
encrypt request
handshake complete
Logged in!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Logged off: 34
    at SteamClient.handlers.(anonymous function) (/home/bot/node_modules/steam/lib/handl    ers/user.js:217:13)
    at SteamClient._netMsgReceived (/home/bot/node_modules/steam/lib/steam_client.js:106    :26)
    at SteamClient.handlers.(anonymous function) (/home/bot/node_modules/steam/lib/steam    _client.js:192:10)
    at SteamClient._netMsgReceived (/home/bot/node_modules/steam/lib/steam_client.js:106    :26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)

**Comment by scholtzm** [comment]
`// Unhandled 'error' event`

Check README for 'error' event.

**Comment by seishun** [comment]
>	[LogonSessionReplaced = 34;](https://github.com/SteamRE/SteamKit/blob/6aa47f764c796a1373a047cd30540c206943fcae/Resources/SteamLanguage/eresult.steamd#L37)

**Comment by strigunov** [comment]
what am I supposed to do

**Comment by seishun** [comment]
You could try not logging into the same account twice.
