### ISSUE TITLE
Error when Starting Bot! [NOOB]

### ISSUE THREAD

**Issue by camao** [seishun/node-steam#187]
Hi Everyone!

Im new to Javascript, and i need some help here :)
So i (almost) copied the Example.js beacuse i wanted to try it out :)

But when i start my bot it gives me this Error ;(

Thanks :)

**ERROR:**
```javascript
/home/ubuntu/workspace/node_modules/steam/node_modules/steam-crypto/index.js:6                                                                                              
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);                                                                                                      
                                 ^                                                                                                                                          
TypeError: Object #<Object> has no method 'publicEncrypt'                                                                                                                   
    at Object.exports.generateSessionKey (/home/ubuntu/workspace/node_modules/steam/node_modules/steam-crypto/index.js:6:34)                                                
    at SteamClient.handlers.(anonymous function) (/home/ubuntu/workspace/node_modules/steam/lib/steam_client.js:226:44)                                                     
    at SteamClient._netMsgReceived (/home/ubuntu/workspace/node_modules/steam/lib/steam_client.js:167:26)                                                                   
    at Connection.emit (events.js:95:17)                                                                                                                                    
    at Connection._readPacket (/home/ubuntu/workspace/node_modules/steam/lib/connection.js:50:8)                                                                            
    at Connection.emit (events.js:92:17)                                                                                                                                    
    at emitReadable_ (_stream_readable.js:427:10)                                                                                                                           
    at emitReadable (_stream_readable.js:423:5)                                                                                                                             
    at readableAddChunk (_stream_readable.js:166:9)                                                                                                                         
    at Connection.Readable.push (_stream_readable.js:128:10)  
```

**MY CODE: **
```javascript
var SteamTradeOffers = require("steam-tradeoffers");
var Steam = require('steam');


var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: 'USERNAME',
    password: 'PASSWORD'
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online);
  }
});
```

**Comment by seishun** [comment]
From README:

>Note: only Node.js v0.12 and io.js v2.x are supported.
