### ISSUE TITLE
Error: .CMsgClientLogon#shaSentryfile is not a field: undefined

### ISSUE THREAD

**Issue by MajorErection** [seishun/node-steam#197]
So, I decided to try this whole thing out and I'm getting this error. I'm fairly new here so please just let me know if I'm doing something wrong. 

C:\MahStuff\node_modules\steam\node_modules\protobufjs\dist\ProtoBuf.js:2539
                            throw Error(this+"#"+keyOrObj+" is not a field: un
                                                         ^
Error: .CMsgClientLogon#shaSentryfile is not a field: undefined
    at Error (native)
    at MessagePrototype.set (C:\BotcoinFork\node_modules\steam\node_modules\prot
obufjs\dist\ProtoBuf.js:2539:58)
    at MessagePrototype.set (C:\BotcoinFork\node_modules\steam\node_modules\prot
obufjs\dist\ProtoBuf.js:2533:38)
    at Message (C:\BotcoinFork\node_modules\steam\node_modules\protobufjs\dist\P
rotoBuf.js:2462:34)
    at SteamUser.logOn (C:\BotcoinFork\node_modules\steam\lib\handlers\user\inde
x.js:33:6)
    at Object.<anonymous> (C:\BotcoinFork\bot.js:45:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by seishun** [comment]
There's no field `shaSentryfile` in [CMsgClientLogon](https://github.com/SteamRE/SteamKit/blob/6aa47f764c796a1373a047cd30540c206943fcae/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L45-L91). Did you mean `sha_sentryfile`?

**Comment by MajorErection** [comment]
oh wow, damn I'm dumb. It was a typo :/
