### ISSUE TITLE
gamesPlayed error

### ISSUE THREAD

**Issue by GabrielLopes-** [seishun/node-steam#198]
Hi, I have an issue trying to launch the game
```
gabriellopes@accel:~/Node.js/node-steam-master$ node steam.js
/home/gabriellopes/Node.js/node-steam-master/node_modules/globaloffensive/index.js:41
		gamesPlayed.call(steam, appids);
		           ^
TypeError: Cannot read property 'call' of undefined
```

```
var fs = require('fs');
var Steam = require('steam');
var GlobalOffensive = require('globaloffensive');

// if we've saved a server list, use it
if (fs.existsSync('servers')) {
  Steam.servers = JSON.parse(fs.readFileSync('servers'));
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamGameCoordinator = new Steam.SteamGameCoordinator(steamClient, 730);
var csgo = new GlobalOffensive(steamClient, 730);

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '',
    password: ''
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
    steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
    steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
    steamClient.gamesPlayed([730]); 
}
});

steamClient.on('servers', function(servers) {
  fs.writeFile('servers', JSON.stringify(servers));
});

steamFriends.on('chatInvite', function(chatRoomID, chatRoomName, patronID) {
  console.log('Got an invite to ' + chatRoomName + ' from ' + steamFriends.personaStates[patronID].player_name);
  steamFriends.joinChat(chatRoomID); // autojoin on invite
});

steamFriends.on('message', function(source, message, type, chatter) {
  // respond to both chat room and private messages
  console.log('Received message: ' + message);
  if (message == 'ping') {
    steamFriends.sendMessage(source, 'pong', Steam.EChatEntryType.ChatMsg); // ChatMsg by default
  }
});

steamFriends.on('chatStateChange', function(stateChange, chatterActedOn, steamIdChat, chatterActedBy) {
  if (stateChange == Steam.EChatMemberStateChange.Kicked && chatterActedOn == steamClient.steamID) {
    steamFriends.joinChat(steamIdChat);  // autorejoin!
  }
});

steamFriends.on('clanState', function(clanState) {
  if (clanState.announcements.length) {
    console.log('Group with SteamID ' + clanState.steamid_clan + ' has posted ' + clanState.announcements[0].headline);
  }
});
```

**Comment by andrewda** [comment]
steamClient.gamesPlayed([730]);

 Should be:

    steamUser.gamesPlayed({
        games_played: [{
            game_id: '730',
        }]
    });

**Comment by GabrielLopes-** [comment]
Thanks for the reply andrew, but now Im receiving syntax error
```
gabriellopes@accel:~/Node.js/node-steam-master$ node steam.js
/home/gabriellopes/Node.js/node-steam-master/steam.js:63
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by andrewda** [comment]
Could I see more of your code, please? It seems as though you might have a stray or extra parenthesis  somewhere in your code.

**Comment by GabrielLopes-** [comment]
```
var fs = require('fs');
var Steam = require('steam');

// if we've saved a server list, use it
if (fs.existsSync('servers')) {
  Steam.servers = JSON.parse(fs.readFileSync('servers'));
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamGameCoordinator = new Steam.SteamGameCoordinator(steamClient, 730);

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '',
    password: ''
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
    steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
    steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
    steamUser.gamesPlayed({
    games_played: [{
        game_id: '730'
    }]
});

steamClient.on('servers', function(servers) {
  fs.writeFile('servers', JSON.stringify(servers));
});

steamFriends.on('chatInvite', function(chatRoomID, chatRoomName, patronID) {
  console.log('Got an invite to ' + chatRoomName + ' from ' + steamFriends.personaStates[patronID].player_name);
  steamFriends.joinChat(chatRoomID); // autojoin on invite
});

steamFriends.on('message', function(source, message, type, chatter) {
  // respond to both chat room and private messages
  console.log('Received message: ' + message);
  if (message == 'ping') {
    steamFriends.sendMessage(source, 'pong', Steam.EChatEntryType.ChatMsg); // ChatMsg by default
  }
});

steamFriends.on('chatStateChange', function(stateChange, chatterActedOn, steamIdChat, chatterActedBy) {
  if (stateChange == Steam.EChatMemberStateChange.Kicked && chatterActedOn == steamClient.steamID) {
    steamFriends.joinChat(steamIdChat);  // autorejoin!
  }
});

steamFriends.on('clanState', function(clanState) {
  if (clanState.announcements.length) {
    console.log('Group with SteamID ' + clanState.steamid_clan + ' has posted ' + clanState.announcements[0].headline);
  }
});
```

**Comment by andrewda** [comment]
steamClient.on('logOnResponse', function(logonResp) {
      if (logonResp.eresult == Steam.EResult.OK) {
        console.log('Logged in!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
        steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
        steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
        steamUser.gamesPlayed({
        games_played: [{
            game_id: '730'
        }]
    });

Should be:

    steamClient.on('logOnResponse', function(logonResp) {
      if (logonResp.eresult == Steam.EResult.OK) {
        console.log('Logged in!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
        steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
        steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
        steamUser.gamesPlayed({
          games_played: [{
            game_id: '730'
          }]
        });
    });

Note the extra `});` .

**Comment by GabrielLopes-** [comment]
```
gabriellopes@accel:~/Node.js/node-steam-master$ node steam.js
/home/gabriellopes/Node.js/node-steam-master/steam.js:33
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
I really dont know whats happening here
```
var fs = require('fs');
var Steam = require('steam');

// if we've saved a server list, use it
if (fs.existsSync('servers')) {
  Steam.servers = JSON.parse(fs.readFileSync('servers'));
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamGameCoordinator = new Steam.SteamGameCoordinator(steamClient, 730);

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '',
    password: ''
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
    steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
    steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
    steamUser.gamesPlayed({
      games_played: [{
        game_id: '730'
      }]
    });
});

steamClient.on('servers', function(servers) {
  fs.writeFile('servers', JSON.stringify(servers));
});

steamFriends.on('chatInvite', function(chatRoomID, chatRoomName, patronID) {
  console.log('Got an invite to ' + chatRoomName + ' from ' + steamFriends.personaStates[patronID].player_name);
  steamFriends.joinChat(chatRoomID); // autojoin on invite
});

steamFriends.on('message', function(source, message, type, chatter) {
  // respond to both chat room and private messages
  console.log('Received message: ' + message);
  if (message == 'ping') {
    steamFriends.sendMessage(source, 'pong', Steam.EChatEntryType.ChatMsg); // ChatMsg by default
  }
});

steamFriends.on('chatStateChange', function(stateChange, chatterActedOn, steamIdChat, chatterActedBy) {
  if (stateChange == Steam.EChatMemberStateChange.Kicked && chatterActedOn == steamClient.steamID) {
    steamFriends.joinChat(steamIdChat);  // autorejoin!
  }
});

steamFriends.on('clanState', function(clanState) {
  if (clanState.announcements.length) {
    console.log('Group with SteamID ' + clanState.steamid_clan + ' has posted ' + clanState.announcements[0].headline);
  }
});
```

**Comment by andrewda** [comment]
You're still missing one closing curly brace to close the if statement.

    steamClient.on('logOnResponse', function(logonResp) {
      if (logonResp.eresult == Steam.EResult.OK) {
        console.log('Logged in!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
        steamFriends.setPersonaName('[Idle] Accel'); // to change its nickname
        steamFriends.joinChat('103582791431621417'); // the group's SteamID as a string
        steamUser.gamesPlayed({
          games_played: [{
            game_id: '730'
          }]
        });
    } // this should do the trick :)
});

**Comment by GabrielLopes-** [comment]
Good to go, thanks buddy! :)

**Comment by scholtzm** [comment]
I'd suggest using proper text editor.

**Comment by seishun** [comment]
Please don't discuss JS syntax here.
