### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by CocaineCowboy** [seishun/node-steam#202]
I get this error when I try to login:

C:\Users\Admin>node idle.js
[STEAM] logging in without sentry
C:\Users\Admin\idle.js:18
        bot.logOn({
            ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\Users\Admin\idle.js:18:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

can anyone tell me whats wrong?

**Comment by seishun** [comment]
There is no logOn function on SteamClient instances, please read the docs.

**Comment by dragonbanshee** [comment]
For bot.logOn({ ... }); to work, you must be using 0.6.8, but you seem to be using 1.0.0, which is why it doesn't work. If you want to install 0.6.8 instead,
```js
$ npm uninstall steam
$ npm install steam@0.6.8
```

**Comment by jeremybras** [comment]
@dragonbanshee Solved my problem, thx!
