### ISSUE TITLE
steamClient not defined? probably a stupid mistake

### ISSUE THREAD

**Issue by ooosssososos** [seishun/node-steam#212]
Code:

```javascript
var Steam = require('steam');
var steamtrade = require('steam-trade');

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
console.log(steamClient);
steamClient.connect();
steamCient.on('connected', function(){
	steamUser.logOn({
		account_name: 'testtraderbotoscar',
		password: ''
	})
});
steamClient.on('logOnResponse', function(){
	console.log("success");
});
```

Error:

```javascript
node app.js 
{ domain: null,
  _events: { message: [Function] },
  _maxListeners: undefined }
/Users/Claire/Desktop/Steambot/app.js:8
steamCient.on('connected', function(){
^
ReferenceError: steamCient is not defined
    at Object.<anonymous> (/Users/Claire/Desktop/Steambot/app.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by buddhapest** [comment]
jeez man, check the spelling of `steamClient`...  ;)

**Comment by seishun** [comment]
>var __steamClient__ = new Steam.SteamClient();
>__steamCient__.on('connected', function(){

I suggest reading the stack trace next time.
