### ISSUE TITLE
Crash when sending message if Steam is offline

### ISSUE THREAD

**Issue by KraXarN** [seishun/node-steam#221]
The not crashes if it tries to send a message while Steam is offline.

Crash log:

Error: Logged off: 2

/home/kraxarn/node_modules/steam/lib/steam_client.js:75
  this._connection.send(Buffer.concat([header.toBuffer(), body.toBuffer()]));
                  ^
TypeError: Cannot read property 'send' of undefined
    at SteamClient._send (/home/kraxarn/node_modules/steam/lib/steam_client.js:75:19)
    at SteamClient.prototype.sendMessage (/home/kraxarn/node_modules/steam/lib/handlers/friends.js:37:10)
    at process.<anonymous> (/home/kraxarn/steambot/node-steam.js:2700:7)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)

**Comment by seishun** [comment]
First, you are using an old and unsupported version of node-steam. Second, it was always explicitly disallowed to call any methods while not logged on.
