### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Rednelss** [seishun/node-steam#224]
connected
encrypt request
handshake complete
logon fail: 5, sessionID: 62941
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Logon fail: 5
    at SteamClient.handlers.(anonymous function) (/home/rednelss/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/home/rednelss/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/home/rednelss/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/home/rednelss/bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection._readPacket (/home/rednelss/bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:67:13)
    at Connection.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:407:10)

**Comment by scholtzm** [comment]
Wrong password.

**Comment by Rednelss** [comment]
Nope! Password correct

**Comment by Rednelss** [comment]
Sorry, my english so bad :D

**Comment by seishun** [comment]
1) Old and unsupported version 2) `InvalidPassword = 5;`

**Comment by danydasda** [comment]
http://csfastpot.win/ look Error: Logon fail: 5
 HELP
