### ISSUE TITLE
Illegal offset: 0 <= 1 (+1) <= 1

### ISSUE THREAD

**Issue by overheader** [seishun/node-steam#234]
Hello

This error occurs when reconnecting to Steam
There was an error:

/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3007
throw(e);
^
RangeError: Illegal offset: 0 <= 1 (+1) <= 1
at RangeError (native)
at module.exports.ByteBufferPrototype.readVarint32 (/home/server/node_modules/steam/node_modules/bytebuffer/dist/ByteBufferNB.js:1469:80)
at ProtoBuf.Reflect.MessagePrototype.decode (/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3281:36)
at Function.Message.decode (/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3002:37)
at Object. (/home/server/node_modules/steam/lib/handlers/user/index.js:41:77)
at SteamClient.netMsgReceived (/home/server/node_modules/steam/lib/steam_client.js:180:28)
at Connection.emit (events.js:107:17)
at Connection._readPacket (/home/server/node_modules/steam/lib/connection.js:50:8)
at Connection.emit (events.js:104:17)
at emitReadable (_stream_readable.js:424:10)
at emitReadable (_stream_readable.js:418:7)

I have an account there is a change at this time on the other, it can somehow affect? It is possible that at the time of the change could be carried out any action with Steam.

**Comment by seishun** [comment]
This is not very informative, please provide a minimal test case.

**Comment by overheader** [comment]
I do not know because of what exactly is going on. Perhaps at this point it is accept offer or getoffer or load my inventory.

This is because when the condition is triggered, then the account changes bot - disconnected from the Steam and reconnected with the new data. After a successful connection, and when should have been executed logOnResponse - gets this error.

Most likely, this is because some action has already begun (accepting trade, loadmyinventory, getoffer), and in this moment there is authorization in the new account.

**Comment by mshi** [comment]
This seems to happen when steam is under load. I experience this almost every afternoon, especially on weekends.

**Comment by seishun** [comment]
>This is because when the condition is triggered, then the account changes bot - disconnected from the Steam and reconnected with the new data. 

Can you show how you reconnect?

**Comment by seishun** [comment]
Interesting, it crashes when it tries to decode the nonce. Could you also add the following above line 41 in lib/handlers/user/index.js?

```js
console.log(header);
console.log(body);
```

**Comment by seishun** [comment]
As discovered in #270, this happens when the method is called while not logged on, which is [disallowed](https://github.com/seishun/node-steam#loggedon). Use the following to prevent this:

```js
if (client.loggedOn) {
  user.requestWebAPIAuthenticateUserNonce(callback);
} else {
  // some logic depending on the context
}
```
