### ISSUE TITLE
Illegal value for [object Object] of type string: boolean (not a string)

### ISSUE THREAD

**Issue by dragonbanshee** [seishun/node-steam#248]
```javascript
Error: Illegal value for [object Object] of type string: boolean (not a string)
    at Error (native)
    at null.<anonymous> (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:1868:114)
    at ProtoBuf.Reflect.ElementPrototype.verifyValue (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:1930:25)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3536:33)
    at MessagePrototype.set (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2542:59)
    at MessagePrototype.set (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2533:38)
    at Message (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2462:34)
    at SteamUser.logOn (/Users/kylesmith/Documents/github/node-steam-chat-bot/node_modules/steam/lib/handlers/user/index.js:33:6)
    at ChatBot.logOn (/Users/kylesmith/Documents/github/node-steam-chat-bot/lib/chatBot.js:253:19)
    at ChatBot._onConnected (/Users/kylesmith/Documents/github/node-steam-chat-bot/lib/chatBot.js:670:7)
```

Getting that error every single time I try to login to Steam after I'm connected.

**Comment by seishun** [comment]
Show how you're calling SteamUser#logOn.

**Comment by dragonbanshee** [comment]
```javascript
try {
			var sha = '';
			if(fs.existsSync(this.sentryFile)) {
				var file = fs.readFileSync(this.sentryFile);
				sha = crypto
					.createHash('sha1')
					.update(file)
				.digest();
			}
			this.steamUser.logOn({ account_name: that.username, password: that.password,
				auth_code: that.guardCode, sha_sentryfile: sha });
		} catch (err) {
			this.winston.error(this.name+"/chatBot.js: Exception trying to connect", err);
		}
```

I am calling this after the 'connected' event is received. That error is thrown in the catch block error.

**Comment by seishun** [comment]
What are the types of `that.username`, `that.password` and `that.guardCode`?

**Comment by dragonbanshee** [comment]
username and password are both strings, while guardCode is either a string or undefined, depending on whether someone specified it.

**Comment by seishun** [comment]
Can you confirm that? Add `console.log(typeof that.username)` and so on before the `logOn` call.

**Comment by dragonbanshee** [comment]
```javascript
string
string
string
object
```

For username, password, guardCode, and sha.

The issue does seem to be gone though, even though I didn't change anything. Could have been a Steam issue.

**Comment by andrewda** [comment]
@dragonbanshee Probably was. Steam was pretty funky on Monday.

**Comment by scholtzm** [comment]
I don't think so, look at the stack trace. It clearly failed to serialize the protobuf message because one of the values was typeof `boolean`.

**Comment by andrewda** [comment]
@scholtzm You're right. I just can't see another way the issue would just "fix itself" unless it was some funny Steam connection issue.
