### ISSUE TITLE
Error: Cannot find module 'steam'

### ISSUE THREAD

**Issue by Rafoute59** [seishun/node-steam#250]
Hello, i'm new here and i have a issue.
When i launch example.js, i have this issue.
module.js:338
    throw err;
          ^
Error: Cannot find module 'steam'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (******/example.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

I have node 0.12.7 and IO 2.0.

**Comment by seishun** [comment]
This is not a help desk.
