### ISSUE TITLE
Error using node steam trade offers getItems()

### ISSUE THREAD

**Issue by StevePavlin** [seishun/node-steam#251]
This only happens after my bots have been online for 12+ hours. Any ideas?

TypeError: Cannot read property 'toString' of null
    at SteamClient._netMsgReceived (/root/Server/node_modules/steam/lib/steam_client.js:94:42)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/Server/node_modules/steam/lib/connection.js:50:8)
    at Connection._readPacket (/root/Server/node_modules/steam/lib/connection.js:53:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
    at Connection.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by seishun** [comment]
You are using an old an unsupported version of node-steam.
