### ISSUE TITLE
Illegal buffer for EMsg.ClientFriendsGroupsList

### ISSUE THREAD

**Issue by shqke** [seishun/node-steam#259]
```javascript
_.on('message', function(header, body, callback) {
    if (header.msg in handlers){
      var data = ByteBuffer.wrap(body, ByteBuffer.LITTLE_ENDIAN)

...

handlers[EMsg.ClientFriendsGroupsList] = function(data) {
```
is throwing an exception with following trace:
```plaintext
C:\Users\user\node_modules\steam\node_modules\steam-resources\node_modules\byte
buffer\dist\ByteBufferNB.js:378
                throw TypeError("Illegal buffer");
                ^

TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Users\user\node_modules\stea
m\node_modules\steam-resources\node_modules\bytebuffer\dist\ByteBufferNB.js:378:
23)
    at Function.Message.decode (C:\Users\user\node_modules\steam\node_modules\s
team-resources\node_modules\protobufjs\dist\ProtoBuf.js:2904:84)
```
What could be the reason?

**Comment by seishun** [comment]
I assume this is SteamClient's 'message' event. Can you add `console.log(body)` above that line?

**Comment by seishun** [comment]
>    at Function.Message.decode (C:\Users\user\node_modules\steam\node_modules\s
team-resources\node_modules\protobufjs\dist\ProtoBuf.js:2904:84)

I do not see a `decode` call in your snippet.

**Comment by shqke** [comment]
console.log(body, typeof body, ByteBuffer.isByteBuffer(body))
      console.log(body instanceof Uint8Array, body instanceof ArrayBuffer, body instanceof Buffer, Object.prototype.toString.call(body))

**Comment by seishun** [comment]
Where's the output? And I'm still waiting for a response to my last comment.

**Comment by shqke** [comment]
Exception is firing before .decode() so i extracted ByteBuffer.wrap() outside of the brackets

```javascript
  _.on('message', function(header, body, callback) {
    if (header.msg in handlers){
      console.log(body, typeof body, ByteBuffer.isByteBuffer(body))
      console.log(body instanceof Uint8Array, body instanceof ArrayBuffer, body instanceof Buffer, Object.prototype.toString.call(body))
      var data = ByteBuffer.wrap(body, ByteBuffer.LITTLE_ENDIAN)
      handlers[header.msg].call(this, ByteBuffer.wrap(body, ByteBuffer.LITTLE_ENDIAN), callback);

...

handlers[EMsg.ClientFriendsGroupsList] = function(data) {
  console.log('cc')
  var list = schema.CMsgClientFriendsGroupsList.decode(data)
```
gives: 
```plaintext
<Buffer 08 00 10 00> 'object' false
true false true '[object Uint8Array]'
cc
C:\Users\user\node_modules\steam\node_modules\steam-resources\node_modules\bytebuffer\dist\ByteBufferNB.js:378
                throw TypeError("Illegal buffer");
                ^

TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Users\user\node_modules\steam\node_modules\steam-resources\node_modules\bytebuffer\dist\ByteBufferNB.js:378:
23)
    at Function.Message.decode (C:\Users\user\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2904:84)
    at SteamClient.handlers.(anonymous function) (C:\Users\user\node-steam-includes.js:75:49)
    at SteamClient.<anonymous> (C:\Users\user\node-steam-includes.js:66:28)
    at emitThree (events.js:102:20)
```

**Comment by seishun** [comment]
My guess is that you're using an old version of ByteBuffer to wrap the Buffer, and it's not recognized by the ByteBuffer used by ProtoBuf.js.

Anyway, this is not a node-steam issue since `body` is apparently received correctly - what you do with it is up to you. I would like to note though that you don't need to wrap the Buffer before passing it to decode.

**Comment by shqke** [comment]
It was outdated, thanks.
