### ISSUE TITLE
Reusing old sentry file?

### ISSUE THREAD

**Issue by StevePavlin** [seishun/node-steam#272]
I just upgraded to the newest version of node-steam and node-steam-trade-offers. Both these libraries worked properly prior to upgrading but now I recieve this in my logs when attempting to login. It seems like it can't recognize the old sentry files?

{ eresult: 63,
  email_domain: 'gmail.com',
  eresult_extended: 63,
  client_supplied_steamid: 'XXX',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }
[2015-10-23 11:18:48] Error: Disconnected
    at SteamClient._disconnected (c:\inetpub\wwwroot\socketio\node_modules\steam\lib\steam_client.js:186:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

Here is my code:
```
var logOnOptions = {
        account_name: accountName,
        password: password
    };

    console.log(getSHA1(fs.readFileSync(displayName + '.bot')));

    try {
        logOnOptions.sha_sentryfile = getSHA1(fs.readFileSync(displayName + '.bot'));
    } catch (e) {
        if (authCode !== '') {
            logOnOptions.auth_code = authCode;
        }
    }

    console.log(logOnOptions);


    // if we've saved a server list, use it
    if (fs.existsSync('servers')) {
        Steam.servers = JSON.parse(fs.readFileSync('servers'));
    }

    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);
    var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
    var offers = new SteamTradeOffers();
    this.offers = offers;


    steamClient.connect();
    steamClient.on('connected', function () {
        steamUser.logOn(logOnOptions);
    });


    steamClient.on('logOnResponse', function (logonResp) {
        console.log(logonResp)
        if (logonResp.eresult === Steam.EResult.OK) {
            console.log('Logged in!');
            steamFriends.setPersonaState(Steam.EPersonaState.Online);


            steamWebLogOn.webLogOn(function (sessionID, newCookie) {
                getSteamAPIKey({
                    sessionID: sessionID,
                    webCookie: newCookie
                }, function (err, APIKey) {
                    offers.setup({
                        sessionID: sessionID,
                        webCookie: newCookie,
                        APIKey: APIKey
                    }, function () {
                          console.log("Ready");
                        };
                    });
                });

            });
        }
    });
    steamClient.on('servers', function(servers) {
        fs.writeFile('servers', JSON.stringify(servers));
    });

    steamUser.on('updateMachineAuth', function(sentry, callback) {
        fs.writeFileSync(displayName + '.bot', sentry.bytes);
        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read();
    }

```

**Comment by scholtzm** [comment]
Old node-steam provided SHA-1 directly.

This will work:

`// the '*.bot' file contains pre-calculated SHA-1`
`logOnOptions.sha_sentryfile = fs.readFileSync(displayName + '.bot');`

I'm sure you can figure out how to fix your `updateMachineAuth` event handler.

You will most likely want to switch to storing full sentry files rather than hashes later on.

**Comment by seishun** [comment]
^

And it was all described in the [release notes](https://github.com/seishun/node-steam/releases/tag/v1.0.0).
