### ISSUE TITLE
Error Logon fail: 5 even with correct password

### ISSUE THREAD

**Issue by ADAMPOKE111** [seishun/node-steam#278]
Using node 0.12.7 (stable) when I run the bot with the correct steamguard code and account credentials and sentry file supplied I get this error:

`Error: Logon fail: 5
    at SteamClient.handlers.(anonymous function) (/root/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/root/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/root/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/root/bot/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)`

**Comment by seishun** [comment]
1. Old and unsupported version of node-steam
2. Steam issue, not library issue

**Comment by danydasda** [comment]
Error: Logon fail: 5
HELP
