### ISSUE TITLE
events.js:85 Catching the error

### ISSUE THREAD

**Issue by Kruemmelmonster** [seishun/node-steam#283]
Hello Guys,

i know that this is not the right place to ask for advise but this seems like a bug.

Whenever i try to login for the first time with a User that has SteamGuard enabled i get the usual Error 63 but it also crashes with the errormessage:

```
events.js:85
Error: Disconnected
    throw er; //Unhandled 'error' event
    at SteamClient._disconnected (C:\test\node_modules\steam\lib\steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
```

for reference this is my Code that i test this error with: 

```
var logOnOptions = {
    account_name: 'test',
    password: '123',
    sha_sentryfile: null
};

var SteamGuardCode = '';

try {
    logOnOptions.sha_sentryfile = fs.readFileSync('sentry');
} catch (e) {
    if (SteamGuardCode !== '') {
        logOnOptions.auth_code = SteamGuardCode;
    }
}

steamClient.connect();
steamClient.on('connected', function () {
    steamUser.logOn(logOnOptions);
});

steamClient.on('logOnResponse', function (res) {
    if (res.eresult == Steam.EResult.OK) {
        console.log('Logged in!');
    }
    else if (res.eresult == Steam.EResult.AccountLogonDenied) {
        console.log('SteamGuard');
    }
});

steamUser.on('error', function (error) {
    console.dir(error);
});
```

What am i doing wrong? I am reading the documentation but cant get any clue out of it

Thanks in advance,
~Kru

**Comment by seishun** [comment]
['error'](https://github.com/seishun/node-steam#error) is an event on SteamClient, not SteamUser.

**Comment by Kruemmelmonster** [comment]
holy crap i am stupid sorry for taking up your time :smile:
