### ISSUE TITLE
Steam Error: Logon fail: 85

### ISSUE THREAD

**Issue by hicior103** [seishun/node-steam#310]
Hello, when the bot tries to log to steam i'm getting this error:
```
socket timed out
socket closed
connecting to 146.66.152.14:27019
socket timed out
socket closed
connecting to 146.66.152.13:27018
socket timed out
socket closed
connecting to 72.165.61.175:27018
connected
encrypt request
handshake complete
logon fail: 85, sessionID: 3808355
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:78:13)
    at Connection.emit (events.js:170:7)
    at Connection._readPacket (/var/www/bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:68:13)
    at Connection.emit (events.js:167:7)
    at emitReadable_ (_stream_readable.js:412:10)
```

* My user name + password are good
* Auth code is good
* Api key is good
* DB info is good

PLEASE HELP.

**Comment by seishun** [comment]
Old and unsupported version of node-steam.

**Comment by andrewda** [comment]
Also leaked code.

**Comment by hicior103** [comment]
What do you mean? @andrewda
