### ISSUE TITLE
ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by hicior103** [seishun/node-steam#311]
I fresh installed node-steam and i get this error

```
/var/www/bot/node_modules/steam/node_modules/steam-resources/steam_language_parser/index.js:8
process.chdir(languagePath);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/var/www/bot/node_modules/steam/node_modules/steam-resources/steam_language_parser/index.js:8:9)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/var/www/bot/node_modules/steam/node_modules/steam-resources/index.js:81:1)
    at Module._compile (module.js:399:26)

```

**Comment by hicior103** [comment]
ref

**Comment by SephirothSG** [comment]
This has been asked many times, please learn to search.

**Comment by seishun** [comment]
Did you install from npm or from git?

**Comment by hicior103** [comment]
i installed it from git and then used npm install inside it

**Comment by jabbink** [comment]
Did you run `npm install` from within `steam/node_modules/steam-resources` as well?

**Comment by hicior103** [comment]
no, should I?

**Comment by seishun** [comment]
You should read the README.

>Note: when installing from git, you have to additionally run npm install inside steam/node_modules/steam-resources to run the prepublish script (see npm/npm#3055). It pulls Steam resources (Protobufs and SteamLanguage) from SteamKit2 and requires svn.

**Comment by hicior103** [comment]
When i make that I get an error:

Note:
I have svn installed.
```
npm WARN lifecycle steam-resources@1.0.0~prepublish: cannot run in wd %s %s (wd=%s) steam-resources@1.0.0 svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language /var/www/bot/node_modules/steam/node_modules/steam-resources

```

**Comment by seishun** [comment]
Because you're [running as root](https://www.google.com/search?q=npm+cannot+run+in+wd).
