### ISSUE TITLE
Error: steam.logOn is not a function

### ISSUE THREAD

**Issue by hicior103** [seishun/node-steam#312]
```
steam.logOn(logOnOptions);
      ^

TypeError: steam.logOn is not a function
    at Object.<anonymous> (/var/www/bot/tradebot.js:54:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by hicior103** [comment]
how can i upgrade this code?, when i downgraded node-steam to 0.6.8 it even not run

**Comment by hicior103** [comment]
please help
