### ISSUE TITLE
Linux: error with steam-crypto

### ISSUE THREAD

**Issue by tionsys** [seishun/node-steam#331]
Hey,

used this library under windows, works like a charm. When uploading the same code on a linux machine it throws an error.
Reinstalling on linux machine with npm doesn't change anything...

Tryed reinstalling like this:
> npm remove steam
> npm install steam

Error:
/node_modules/steam/node_modules/steam-crypto/index.js:6
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/node_modules/steam/node_modules/steam-crypto/index.js:6:34)
    at SteamClient.handlers.(anonymous function) (/node_modules/steam/lib/steam_client.js:216:44)
    at SteamClient._netMsgReceived (/node_modules/steam/lib/steam_client.js:157:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Connection.Readable.push (_stream_readable.js:130:10)

**Comment by seishun** [comment]
You're using an old version of Node.js.
