### ISSUE TITLE
Where problem?

### ISSUE THREAD

**Issue by m4rve1337** [seishun/node-steam#351]
I created bot and after:
`connected
encrypt request
C:\Users\user\Desktop\myBot\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .CMsgClientLogon#accountName is not a field: undefined
    at Error (native)
    at MessagePrototype.set (C:\Users\user\Desktop\myBot\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2440:35)
    at MessagePrototype.set (C:\Users\user\Desktop\myBot\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2434:38)
    at Message (C:\Users\user\Desktop\myBot\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2363:34)
    at SteamUser.logOn (C:\Users\user\Desktop\myBot\node_modules\steam\lib\handlers\user\index.js:33:6)
    at SteamClient.<anonymous> (C:\Users\user\Desktop\myBot\app.js:25:13)
    at emitNone (events.js:72:20)
    at SteamClient.emit (events.js:166:7)
    at SteamClient.handlers.(anonymous function) (C:\Users\user\Desktop\myBot\node_modules\steam\lib\steam_client.js:243:8)
    at SteamClient._netMsgReceived (C:\Users\user\Desktop\myBot\node_modules\steam\lib\steam_client.js:157:26)`

**Comment by seishun** [comment]
There is no `accountName` field in `CMsgClientLogon`.
