### ISSUE TITLE
Throw er; // Unhandled 'error' event | Node-steam 

### ISSUE THREAD

**Issue by csgoready** [seishun/node-steam#359]
Hi!

I am working on a CS:GO jackpot website, but I am having some struggles with the steam bot.

I got the csgo.network 1.4 jackpot downloaded. But when I installed it and followed the instructions and wanted to test the bot. I came across this error:

`root@vps280311:/var/www/bot#` node sell.js
socket timed out
socket closed
connecting to 146.66.152.12:27018
socket timed out
socket closed
connecting to 72.165.61.175:27017
connected
encrypt request
handshake complete
logon fail: 5, sessionID: 4423069
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 5
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection._readPacket (/var/www/bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:67:13)
    at Connection.emit (events.js:166:7)
    at emitReadable_ `(_stream_readable.js:419:10)`

Can anybody please help me please? Would be appreciated! :)

- Justin, CSGO-READY.EU

**Comment by seishun** [comment]
Old and unsupported version of node-steam.

**Comment by csgoready** [comment]
And how do I update it? :)

**Comment by danydasda** [comment]
I have the same problem
passwords are to increase 5 times checked
the only thing that can be anything from steam guard
