### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by seupoj** [seishun/node-steam#36]
Last login: Tue Oct  8 21:47:14 on ttys000
karans-imac:~ karan$ npm install steam
npm http GET https://registry.npmjs.org/steam
npm http 304 https://registry.npmjs.org/steam
npm http GET https://registry.npmjs.org/protobuf
npm http GET https://registry.npmjs.org/adm-zip
npm http GET https://registry.npmjs.org/crc
npm http GET https://registry.npmjs.org/ursa
npm http GET https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/adm-zip
npm http 304 https://registry.npmjs.org/protobuf
npm http 304 https://registry.npmjs.org/ursa
npm http 304 https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/crc
npm WARN engine protobuf@0.8.7: wanted: {"node":">= 0.8.0 < 0.9.0"} (current: {"node":"v0.10.20","npm":"1.3.11"})

> ursa@0.8.0 install /Users/karan/node_modules/steam/node_modules/ursa
> node-gyp configure build && node install.js

npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug

> protobuf@0.8.7 install /Users/karan/node_modules/steam/node_modules/protobuf
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/karan/node_modules/steam/node_modules/ursa
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 502, in gyp_main
    options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 131, in Load
    params['parallel'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2568, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 341, in LoadTargetBuildFile
    d = gyp.common.RelativePath(depth, os.path.dirname(build_file_path))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 25, in **call**
    result = self.func(*args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 131, in RelativePath
    path = os.path.realpath(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 375, in realpath
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 347, in abspath
OSError: [Errno 2] No such file or directory
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/karan/node_modules/steam/node_modules/protobuf
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bindings

> ref@0.1.3 install /Users/karan/node_modules/steam/node_modules/ref
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/karan/node_modules/steam/node_modules/ref) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/karan/node_modules/steam/node_modules/ref
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! not ok code 0
karans-imac:~ karan$ 

Hello what is the fix for this error i am using mac version do you support mac also 
Thanks  in advance 
Frost

**Comment by NavyCo** [comment]
When I do this...
```node
var Steam = require('steam');
var bot = new Steam.SteamClient();
bot.logOn({
    accountName: 'nico55538',
    password: '**********'
});
bot.on('loggedOn', function() {
    console.log('It Worked!')
});
```
It returns this...
```node
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (C:\Users\Nicholas\node_modules\steam\lib\steam_client.js:150:42)
    at SteamClient._netMsgReceived (C:\Users\Nicholas\node_modules\steam\lib\steam_client.js:106:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (C:\Users\Nicholas\node_modules\steam\lib\connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```
Whats the problem here???
