### ISSUE TITLE
Throw er; // Unhandled 'error' event | Node-steam [RE-OPEN]

### ISSUE THREAD

**Issue by csgoready** [seishun/node-steam#360]
Hi! My issue just got closed, but I want to re-open it again because I did what the person that responded asked. But it still doesn't work.

So I updated my node to the latest version, installed all the packages I needed again (such as steamcommunity, fs and readline).

But I am getting a new error:

root@vps280311:/var/www/bot# node sell.js
socket timed out
socket closed
connecting to 72.165.61.174:27018
connected
encrypt request
handshake complete
logon fail: 5, sessionID: 4303785
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 5
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/var/www/bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection._readPacket (/var/www/bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:438:10)
root@vps280311:/var/www/bot#

Can someone help me please? And not just directly shut the issue down if it isn't fixed yet ;)

Thanks,

Justin

**Comment by csgoready** [comment]
because I have node v6.0.0 installed now :)

**Comment by seishun** [comment]
You're still using an old version of node-steam. The issue tracker is for library issues and is not a helpdesk.

**Comment by danydasda** [comment]
work?
