### ISSUE TITLE
example.js does not work

### ISSUE THREAD

**Issue by rafalolszewskii** [seishun/node-steam#380]
Your example.js does not work, it give error: 
```

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (/home/rafal/csgoidle/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12)
```

**Comment by seishun** [comment]
https://github.com/seishun/node-steam#error
