### ISSUE TITLE
Steam-Crypto Error

### ISSUE THREAD

**Issue by ThatBossGuy** [seishun/node-steam#398]
Hi, I am currently receiving this error with Steam-Crypto I've checked and my Node version should be the latest thanks for any help you can provide!

/var/www/bot/node_modules/steam-crypto/index.js:6
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
                                 ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/var/www/bot/node_modules/steam-crypto/index.js:6:34)
    at CMClient.handlers.(anonymous function) (/var/www/bot/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:315:31)
    at CMClient._netMsgReceived (/var/www/bot/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:242:24)
    at TCPConnection.EventEmitter.emit (events.js:95:17)
    at TCPConnection._readPacket (/var/www/bot/node_modules/steam-user/node_modules/steam-client/lib/tcp_connection.js:59:7)
    at TCPConnection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at TCPConnection.Readable.push (_stream_readable.js:127:10)

**Comment by seishun** [comment]
What's your node.js version?

**Comment by ThatBossGuy** [comment]
Well, it looks like I've come across a new error when I do node -version nothing happens do you know where I could get help with that?

**Comment by seishun** [comment]
`node --version`

**Comment by ThatBossGuy** [comment]
That seems to be not working either which is really weird as I installed it about 2hours ago.

**Comment by seishun** [comment]
Can you provide a screenshot or a video?

**Comment by ThatBossGuy** [comment]
Heres a video https://youtu.be/qWN9MPn_nJ8 btw I just want to say I'm really appreciative towards you helping me out :)

**Comment by seishun** [comment]
Try `nodejs --version` or rebooting.

**Comment by ThatBossGuy** [comment]
Ok, my nodejs --version works and it is v0.10.25

**Comment by seishun** [comment]
Well that's really old. You need at least v4.1.1.

**Comment by jabbink** [comment]
It looks like you installed nodejs via `apt-get` on Debian/Ubuntu, @ThatBossGuy 

As I see that you are using DigitalOcean, feel free to take this guide hosted by them (should work on their systems, and actually anywhere else).

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

Also uninstall that old 0.10 version.
