### ISSUE TITLE
TradeBot please help me idk 

### ISSUE THREAD

**Issue by Helling2017** [seishun/node-steam#413]
Error: Cannot find module 'steam-user'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\e18mi\Desktop\TradeBot\tradebot\bot.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

C:\Users\e18mi\Desktop\TradeBot\tradebot>f

**Comment by andrewda** [comment]
This is not an issue with `node-steam` in the slightest. You need to `npm install steam-user`, but this something very simple in Node.js. I recommend you learn the basics of Node.js before jumping into something complex like a Steam bot.

**Comment by Helling2017** [comment]
@andrewda Do you make trade bots for free idk why im getting 100 errors msg me if u can bud
