### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rotteborg** [seishun/node-steam#414]
not sure where to ask this but I'm getting this error and I don't know how to fix it.

module.js:657
    throw err;
    ^

SyntaxError: C:\Users\L\Desktop\steam bot\config.json: Unexpected string in JSON at position 108
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\L\Desktop\steam bot\bot.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

C:\Users\L\Desktop\steam bot>pause

**Comment by andrewda** [comment]
This has absolutely nothing to do with `node-steam`. Your own code (in the `config.json` file) has a typo. I'd suggest learning to completely understand the errors before making issue reports.

**Comment by rotteborg** [comment]
sorry but can you help me with this?

**Comment by andrewda** [comment]
Your `config.json` file has a typo in it that causes it to be invalid.

**Comment by rotteborg** [comment]
oh, thanks alot.
