### ISSUE TITLE
Can't login bot, error 85

### ISSUE THREAD

**Issue by EnderWinner** [seishun/node-steam#424]
connecting to 72.165.61.188:27017
socket timed out
socket closed
connecting to 72.165.61.185:27017
connected
encrypt request
handshake complete
logon fail: 85, sessionID: 1768419713
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (C:\Users\sanik\Desktop\самописы\нихэ\node_modules\steam\lib\handlers\user.js:178:11)
    at SteamClient._netMsgReceived (C:\Users\sanik\Desktop\самописы\нихэ\node_modules\steam\lib\steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\sanik\Desktop\самописы\нихэ\node_modules\steam\lib\steam_client.js:192:10)
    at SteamClient._netMsgReceived (C:\Users\sanik\Desktop\самописы\нихэ\node_modules\steam\lib\steam_client.js:106:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection._readPacket (C:\Users\sanik\Desktop\самописы\нихэ\node_modules\steam\lib\connection.js:50:8)
    at emitNone (events.js:106:13)
    at Connection.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)

**Comment by seishun** [comment]
Outdated and unsupported node-steam version.
