### ISSUE TITLE
Error: Expecting terminator

### ISSUE THREAD

**Issue by essramos** [seishun/node-steam#436]
Hello, 

I am having this issue with require('Steam'). I followed the steps and run the `npm install` on the steam-resources folder. This is the exact stack trace. 

```
C:\Users\user\Desktop\test\node-dota2\node_modules\steam\node_modules\st
eam-resources\steam_language_parser\parser\token_analyzer.js:188
    throw new Error("Expecting " + name);
    ^

Error: Expecting terminator
    at expect (C:\Users\user\Desktop\test\node-dota2\node_modules\steam\
node_modules\steam-resources\steam_language_parser\parser\token_analyzer.js:188:
11)
    at parseInnerScope (C:\Users\user\Desktop\test\node-dota2\node_modul
es\steam\node_modules\steam-resources\steam_language_parser\parser\token_analyze
r.js:161:7)
    at Object.exports.analyze (C:\Users\user\Desktop\test\node-dota2\nod
e_modules\steam\node_modules\steam-resources\steam_language_parser\parser\token_
analyzer.js:103:15)
    at Object.exports.analyze (C:\Users\user\Desktop\test\node-dota2\nod
e_modules\steam\node_modules\steam-resources\steam_language_parser\parser\token_
analyzer.js:36:33)
    at Object.exports.analyze (C:\Users\user\Desktop\test\node-dota2\nod
e_modules\steam\node_modules\steam-resources\steam_language_parser\parser\token_
analyzer.js:36:33)
    at Object.<anonymous> (C:\Users\user\Desktop\test\node-dota2\node_mo
dules\steam\node_modules\steam-resources\steam_language_parser\index.js:14:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by seishun** [comment]
For now I suggest using the npm package, without running `npm install` in steam-resources.

**Comment by essramos** [comment]
thanks, I tried to reinstall again and it worked without having to npm install on the steam-resources folder

**Comment by seishun** [comment]
This was an issue in node-steam-resources. It was fixed in https://github.com/seishun/node-steam-resources/commit/893606cba07885f4b4ca39817ad1ba92d5483c3e and the version was bumped in https://github.com/seishun/node-steam/commit/667abdfb7d57c6ae5fcbd54b600e7abb46e542aa, so it should be good now. I'll be grateful if you give it a try.
