### ISSUE TITLE
GamePlayed Error

### ISSUE THREAD

**Issue by Aka-San** [seishun/node-steam#437]
```
bot.gamesPlayed({
	games_played: [{
		game_id: '15444025664222527488',
		game_extra_info:  '121212'
	}]
});
```
Error:
```
C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2490
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .CMsgClientGamesPlayed.GamePlayed#games_played is not a field: undefined
    at MessagePrototype.set (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2490:35)
    at MessagePrototype.set (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2483:38)
    at new Message (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2411:34)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:1925:28)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:3480:43)
    at MessagePrototype.set (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2493:59)
    at new Message (C:\Users\homek\Desktop\test\node_modules\protobufjs\dist\protobuf.js:2415:42)
    at SteamUser._send (C:\Users\homek\Desktop\test\node_modules\steam-user\components\messages.js:160:10)
    at doTheThing (C:\Users\homek\Desktop\test\node_modules\steam-user\components\apps.js:34:8)
    at SteamUser.gamesPlayed (C:\Users\homek\Desktop\test\node_modules\steam-user\components\apps.js:30:3)
```

**Comment by seishun** [comment]
Per the stack trace, you're not using node-steam, but some other library.
