### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ghost** [seishun/node-steam#478]
/home/unknown/Schreibtisch/STEAMBOT/node_modules/steam/node_modules/steam-resources/index.js:39
  var builder = ProtoBuf.newBuilder();
                         ^

TypeError: ProtoBuf.newBuilder is not a function
    at loadProtoFiles (/home/unknown/Schreibtisch/STEAMBOT/node_modules/steam/node_modules/steam-resources/index.js:39:26)
    at Object.<anonymous> (/home/unknown/Schreibtisch/STEAMBOT/node_modules/steam/node_modules/steam-resources/index.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/unknown/Schreibtisch/STEAMBOT/node_modules/steam/lib/steam_client.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)

**Comment by seishun** [comment]
It works for me. Please provide steps to reproduce.

**Comment by ghost** [comment]
before a few days it works perfect now it doesnt work i tried to update it

thx for your fast response

**Comment by seishun** [comment]
You haven't provided steps to reproduce so I can't help you. Try reinstalling or something.
